# Generated by Django 4.2.6 on 2023-10-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('criterion_id', models.AutoField(primary_key=True, serialize=False)),
                ('criterion_type', models.CharField(choices=[('Garment Construction', 'Garment Construction'), ('Fit for category', 'Fit for Category'), ('Innovation & originality', 'Innovation & Originality'), ('Wow factor', 'Wow Factor')], max_length=50)),
                ('criterion_description', models.TextField()),
            ],
        ),
    ]
