# Generated by Django 4.2.6 on 2023-11-06 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_logo_photo'),
        ('criteria', '0002_alter_criterion_criterion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='events.event'),
        ),
    ]
