# Generated by Django 4.2.6 on 2023-10-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('Judge', 'Judge'), ('Adjudicator', 'Adjudicator')], max_length=255)),
                ('profile_photo', models.ImageField(upload_to='users/')),
                ('usr_description', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('organisation_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(default='Australia', max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('notification', models.TextField()),
            ],
        ),
    ]
