# Generated by Django 4.2.6 on 2023-10-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('final_entry_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('organiser_name', models.CharField(max_length=255)),
                ('organiser_contact', models.CharField(max_length=255)),
                ('logo_photo', models.ImageField(upload_to='events/')),
                ('event_description', models.TextField()),
            ],
        ),
    ]
