# Generated by Django 4.2.6 on 2023-10-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_role', models.CharField(choices=[('model', 'Model'), ('volunteer', 'Volunteer'), ('designer', 'Designer')], max_length=50)),
                ('participant_description', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='participants/')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('organisation_name', models.CharField(max_length=100)),
                ('participant_status', models.CharField(choices=[('student', 'Student'), ('emerging', 'Emerging')], max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='Australia', max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('notification', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('judge', 'Judge'), ('adjudicator', 'Adjudicator')], max_length=12)),
                ('profile_photo', models.ImageField(upload_to='users/')),
                ('usr_description', models.TextField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('organisation_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(default='Australia', max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('notification', models.TextField()),
            ],
        ),
    ]
