# Generated by Django 4.2.6 on 2023-10-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='contact_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(default='Australia', max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='organisation_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_role',
            field=models.CharField(choices=[('Model', 'Model'), ('Volunteer', 'Volunteer'), ('Designer', 'Designer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_status',
            field=models.CharField(choices=[('Student', 'Student'), ('Emerging', 'Emerging')], max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='zip_code',
            field=models.CharField(max_length=255),
        ),
    ]
