# Generated by Django 4.2.6 on 2023-10-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_delete_user_alter_participant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='other_role_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_role',
            field=models.CharField(choices=[('Model', 'Model'), ('Volunteer', 'Volunteer'), ('Designer', 'Designer'), ('Other', 'Other')], max_length=255),
        ),
    ]
