# Generated by Django 4.2.6 on 2023-10-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_participant_other_role_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_status',
            field=models.CharField(choices=[('Student', 'Student'), ('Emerging', 'Emerging'), ('Other', 'Other')], max_length=255),
        ),
    ]
