# Generated by Django 4.2.6 on 2023-11-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_alter_participant_participant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(blank=True, default='Australia', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_status',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Emerging', 'Emerging'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='participants/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='zip_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
