# Generated by Django 4.2.6 on 2023-11-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_participant_city_alter_participant_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_role',
            field=models.CharField(blank=True, choices=[('Model', 'Model'), ('Volunteer', 'Volunteer'), ('Designer', 'Designer'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
