# Generated by Django 4.2.6 on 2023-11-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0008_participant_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalNotification',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='other_role_description',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_role',
        ),
    ]
