# Generated by Django 4.2.6 on 2023-11-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0009_delete_globalnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_role',
            field=models.CharField(default='Entrant', max_length=20),
        ),
    ]
