# Generated by Django 4.2.6 on 2023-10-27 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_name', models.CharField(max_length=255)),
                ('entry_photo', models.ImageField(upload_to='entry_photos/')),
                ('entry_audio', models.FileField(upload_to='entry_audios/')),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('entry_status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Review', max_length=255)),
                ('entry_description', models.TextField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
        ),
    ]
