# Generated by Django 4.2.6 on 2023-11-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_audio',
            field=models.FileField(blank=True, null=True, upload_to='entry_audios/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_photo',
            field=models.ImageField(blank=True, null=True, upload_to='entry_photos/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_status',
            field=models.CharField(blank=True, choices=[('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending Review', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
