# Generated by Django 4.2.6 on 2023-11-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
    ]
