# Generated by Django 4.2.6 on 2023-11-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entry_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='run_oder',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
