# Generated by Django 4.2.6 on 2023-11-10 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_entry_run_oder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='run_oder',
            new_name='run_order',
        ),
    ]
