# Generated by Django 4.2.6 on 2023-11-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_rename_run_oder_entry_run_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='models_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
