# Generated by Django 4.2.6 on 2023-11-13 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_entry_models_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 13, 0, 17, 2, 457214, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='update_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 11, 13, 0, 17, 16, 695682, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
