# Generated by Django 4.2.6 on 2023-11-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_award_award_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='participants',
        ),
        migrations.AlterField(
            model_name='award',
            name='award_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
